import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = { title: 'Privacy Policy — Atlas Prime' }

const EFFECTIVE = 'May 7, 2026'
const LAST_UPDATED = 'June 18, 2026'

export default function PrivacyPage() {
  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px 80px' }}>

      {/* Header */}
      <div style={{ marginBottom: 40 }}>
        <Link href="/auth" style={{ fontSize: 13, color: 'var(--text-dim)', textDecoration: 'none', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: 6, marginBottom: 28 }}>
          ← Back
        </Link>
        <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--accent)', marginBottom: 10 }}>
          Legal
        </div>
        <h1 style={{ fontSize: 32, fontWeight: 900, letterSpacing: '-0.02em', marginBottom: 8 }}>
          Privacy Policy
        </h1>
        <p style={{ fontSize: 13, color: 'var(--text-dim)' }}>
          Effective {EFFECTIVE} &nbsp;·&nbsp; Last updated {LAST_UPDATED}
        </p>
      </div>

      <Section title="1. What We Collect">
        <P>We collect information you provide directly, information generated by your use of the Service, and limited technical information.</P>
        <Subsection label="Account information">
          Your email address, name, and authentication credentials (stored and managed by Supabase and, if you use Google sign-in, by Google).
        </Subsection>
        <Subsection label="Fitness profile">
          Sport, training goals, session preferences, workout location, available equipment, injury history, restriction areas, gender, and any notes you provide during onboarding or profile updates.
        </Subsection>
        <Subsection label="Training and activity data">
          Workout logs, completed sessions, set and rep counts, weights recorded, calendar entries, recovery mode status, and any notes you attach to sessions.
        </Subsection>
        <Subsection label="AI-generated content">
          The personalized workout programs, exercise cues, and coaching content generated for your account based on your profile. These are stored so the platform can reference and build on them over time.
        </Subsection>
        <Subsection label="Usage information">
          Pages visited, features used, and session timestamps. We use this to understand how the platform is performing and how to improve it. We do not use third-party advertising trackers.
        </Subsection>
      </Section>

      <Section title="2. How We Use Your Data">
        <UL items={[
          'Generate and deliver personalized workout programs using AI.',
          'Remember your training history and adapt future programming to your progress.',
          'Operate and improve the Service, including debugging, performance monitoring, and feature development.',
          'Send transactional communications (account confirmations, policy updates). We do not send marketing emails without your explicit opt-in.',
          'Enforce our Terms of Service and protect the security of the platform.',
        ]} />
      </Section>

      <Section title="3. Admin Access and Impersonation">
        <P><strong style={{ color: 'var(--text)' }}>This section is important.</strong> Atlas Prime platform administrators have the technical ability to temporarily access your account in a read/support mode for quality assurance and customer support purposes.</P>
        <P>Every impersonation session is subject to the following safeguards:</P>
        <UL items={[
          'Full audit log: every session records the administrator\'s identity, the time the session started and ended, the stated reason for access, and every data write made during the session.',
          'Time-limited: sessions expire automatically (maximum 2 hours) and cannot be silently extended.',
          'Write logging: any data created or deleted during a session is logged and reversible for 30 days.',
          'No credential access: administrators cannot view or change your password or any payment credentials through this feature.',
          'Password and payment data are never accessible through impersonation.',
        ]} />
        <P>We will only use impersonation to diagnose bugs you report, verify data integrity, or respond to a support request. We will not use it to read your data for advertising, profiling, or any purpose unrelated to operating the Service.</P>
      </Section>

      <Section title="4. Data Sharing">
        <P>We do not sell your personal data. We share it only with the following service providers who help us operate the platform:</P>
        <UL items={[
          'Supabase — database hosting, authentication, and file storage. Data is stored in secure cloud infrastructure.',
          'Anthropic — the AI that generates your workout programs. Your fitness profile and relevant training context are sent to Anthropic\'s API to produce personalized content. Anthropic\'s privacy policy governs their handling of API data.',
          'OpenAI — provides spoken (text-to-speech) narration of exercise instructions and generates the text embeddings used to retrieve relevant coaching knowledge. Limited exercise and coaching text is sent to OpenAI\'s API. OpenAI\'s privacy policy governs their handling of API data.',
          'Google — if you sign in with Google, your Google account information is shared with Google per their privacy policy.',
          'Vercel — the platform that hosts and serves the Atlas Prime web application.',
        ]} />
        <P>We may disclose data if required by law, court order, or to protect the safety of our users or the public.</P>
      </Section>

      <Section title="5. Data Retention">
        <P>We retain your data for as long as your account is active. If you delete your account, we will delete your personal data within 30 days, except where retention is required by law or for legitimate business purposes such as fraud prevention.</P>
        <P>Workout logs and training history are retained for the life of your account so the AI can build progressively on your history. You can delete individual log entries at any time from the History page.</P>
        <P>Admin impersonation audit logs are retained for a minimum of 90 days for security and accountability purposes.</P>
      </Section>

      <Section title="6. Your Rights">
        <P>Depending on your location, you may have rights including:</P>
        <UL items={[
          'Access: request a copy of the personal data we hold about you.',
          'Correction: request that inaccurate data be corrected.',
          'Deletion: request that your account and associated data be deleted.',
          'Portability: request your data in a machine-readable format.',
          'Objection: object to certain processing activities.',
        ]} />
        <P>To exercise any of these rights, contact us at the address in Section 9. We will respond within 30 days.</P>
      </Section>

      <Section title="7. Security">
        <P>We implement industry-standard security measures including encrypted data storage (Supabase), row-level security policies that enforce strict access controls, and the admin safeguards described in Section 3. No system is perfectly secure; we encourage you to use a strong, unique password and enable two-factor authentication on your email account.</P>
      </Section>

      <Section title="8. Children">
        <P>The Service is not directed at children under 13. We do not knowingly collect personal data from children under 13. If we learn that we have done so, we will delete it promptly.</P>
      </Section>

      <Section title="9. Changes to This Policy">
        <P>We may update this policy as the Service evolves. Significant changes will be communicated via email or an in-app notice before they take effect. Your continued use after the effective date constitutes acceptance.</P>
      </Section>

      <Section title="10. Contact">
        <P>For privacy questions, data requests, or to report a concern, use the feedback option in the Account page inside the app or the support channel listed there.</P>
      </Section>

      <div style={{ marginTop: 40, paddingTop: 24, borderTop: '1px solid var(--border)', display: 'flex', gap: 20, flexWrap: 'wrap' }}>
        <Link href="/legal/terms" style={{ fontSize: 13, color: 'var(--accent)', textDecoration: 'none', fontWeight: 600 }}>
          Terms of Service →
        </Link>
        <Link href="/auth" style={{ fontSize: 13, color: 'var(--text-dim)', textDecoration: 'none' }}>
          Back to sign up
        </Link>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 16, fontWeight: 700, color: 'var(--text)', marginBottom: 12, letterSpacing: '-0.01em' }}>
        {title}
      </h2>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {children}
      </div>
    </div>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ fontSize: 14, color: 'var(--text-mid)', lineHeight: 1.75 }}>{children}</p>
}

function Subsection({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div style={{ paddingLeft: 16, borderLeft: '2px solid var(--border2)' }}>
      <p style={{ fontSize: 13, fontWeight: 700, color: 'var(--text)', marginBottom: 3 }}>{label}</p>
      <p style={{ fontSize: 14, color: 'var(--text-mid)', lineHeight: 1.7 }}>{children}</p>
    </div>
  )
}

function UL({ items }: { items: string[] }) {
  return (
    <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 6 }}>
      {items.map((item, i) => (
        <li key={i} style={{ fontSize: 14, color: 'var(--text-mid)', lineHeight: 1.7 }}>{item}</li>
      ))}
    </ul>
  )
}
