'use client'
import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'

type KnowledgeStat = { category: string; count: number }
type FlaggedItem = {
  id: string
  category: string
  title: string
  content: string
  flag_reason: string
  suggested_content: string
  flagged_at: string
  version: number
}

const CATEGORY_META: Record<string, { label: string; icon: string; color: string }> = {
  training_principle: { label: 'Training Principles',  icon: '🧠', color: 'var(--accent)' },
  sport_protocol:     { label: 'Sport Protocols',      icon: '🏆', color: 'var(--green)' },
  rehab_protocol:     { label: 'Rehab Protocols',      icon: '🩹', color: 'var(--blue)' },
  exercise:           { label: 'Exercise Library',     icon: '💪', color: 'var(--orange)' },
  nutrition_principle:{ label: 'Nutrition Principles', icon: '🥗', color: 'var(--yellow)' },
}

export default function APIETab() {
  const [stats, setStats] = useState<KnowledgeStat[]>([])
  const [loading, setLoading] = useState(true)
  const [seeding, setSeeding] = useState(false)
  const [seedResult, setSeedResult] = useState<string | null>(null)

  // Phase 4 — Curator
  const [flaggedItems, setFlaggedItems] = useState<FlaggedItem[]>([])
  const [curating, setCurating] = useState(false)
  const [curateResult, setCurateResult] = useState<string | null>(null)
  const [reviewingId, setReviewingId] = useState<string | null>(null)
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const [editContent, setEditContent] = useState<Record<string, string>>({})

  async function loadStats() {
    setLoading(true)
    try {
      const { data } = await supabase
        .from('knowledge_items')
        .select('category')
      if (data) {
        const counts: Record<string, number> = {}
        for (const row of data) {
          counts[row.category] = (counts[row.category] ?? 0) + 1
        }
        setStats(Object.entries(counts).map(([category, count]) => ({ category, count })))
      }
    } finally {
      setLoading(false)
    }
  }

  async function loadFlagged() {
    const { data } = await supabase
      .from('knowledge_items')
      .select('id, category, title, content, flag_reason, suggested_content, flagged_at, version')
      .eq('flagged_for_review', true)
      .order('flagged_at', { ascending: false })
    if (data) setFlaggedItems(data as FlaggedItem[])
  }

  useEffect(() => {
    loadStats()
    loadFlagged()
  }, [])

  async function runSeed() {
    setSeeding(true)
    setSeedResult(null)
    try {
      const res = await fetch('/api/admin/seed-knowledge', { method: 'POST' })
      const data = await res.json()
      setSeedResult(data.message ?? data.error ?? 'Done')
      await loadStats()
    } catch (e) {
      setSeedResult(String(e))
    } finally {
      setSeeding(false)
    }
  }

  async function runCurator() {
    setCurating(true)
    setCurateResult(null)
    try {
      const res = await fetch('/api/admin/curate-knowledge', { method: 'POST' })
      const data = await res.json()
      setCurateResult(data.message ?? data.error ?? 'Done')
      await loadFlagged()
    } catch (e) {
      setCurateResult(String(e))
    } finally {
      setCurating(false)
    }
  }

  async function reviewItem(id: string, action: 'accept' | 'dismiss') {
    setReviewingId(id)
    try {
      const body: Record<string, string> = { id, action }
      if (action === 'accept' && editContent[id]) body.custom_content = editContent[id]
      await fetch('/api/admin/review-knowledge', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      setFlaggedItems(prev => prev.filter(i => i.id !== id))
      setExpandedId(null)
    } finally {
      setReviewingId(null)
    }
  }

  const totalItems = stats.reduce((s, r) => s + r.count, 0)
  const hasData = totalItems > 0

  return (
    <div>
      <div style={{ marginBottom: 24 }}>
        <h2 style={{ fontSize: 22, fontWeight: 900, letterSpacing: '-0.02em', marginBottom: 4 }}>
          Multi-agent Intelligence Engine
        </h2>
        <p style={{ fontSize: 13, color: 'var(--text-dim)', lineHeight: 1.6 }}>
          APIE Phases 1–4 — Domain Knowledge Store + Agent Council + Knowledge Curator. Plans are
          generated by a 6-agent pipeline backed by a vector knowledge store that autonomously
          monitors itself for accuracy.
        </p>
      </div>

      {/* Architecture diagram */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: '20px', marginBottom: 20 }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 16 }}>
          Generation Pipeline
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
          {[
            { icon: '🗄️', label: 'Knowledge Store', sub: 'pgvector retrieval', color: 'var(--blue)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '💪', label: 'S&C Agent', sub: 'Drafts the plan', color: 'var(--accent)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '🩹', label: 'PT/Rehab Agent', sub: 'Safety (injured only)', color: 'var(--blue)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '🏆', label: 'Sports Specialist', sub: 'Sport-specific depth', color: 'var(--orange)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '🧘', label: 'Mobility Agent', sub: 'Movement quality', color: 'var(--purple)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '🧠', label: 'Mindset Agent', sub: 'Warrior philosophy', color: 'var(--accent)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '🔋', label: 'Recovery Agent', sub: 'Rest day science', color: 'var(--green)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '✅', label: 'Final Plan', sub: 'Returned to athlete', color: 'var(--yellow)' },
          ].map((step, i) =>
            step.label ? (
              <div key={i} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, padding: '10px 14px', background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: 12, minWidth: 110 }}>
                <span style={{ fontSize: 18 }}>{step.icon}</span>
                <span style={{ fontSize: 11, fontWeight: 800, color: step.color }}>{step.label}</span>
                <span style={{ fontSize: 10, color: 'var(--text-dim)', textAlign: 'center' }}>{step.sub}</span>
              </div>
            ) : (
              <span key={i} style={{ fontSize: 18, color: 'var(--text-dim)' }}>→</span>
            )
          )}
        </div>
      </div>

      {/* Knowledge store stats */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: '20px', marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 4 }}>
              Knowledge Store
            </div>
            <div style={{ fontSize: 28, fontWeight: 900, color: hasData ? 'var(--accent)' : 'var(--text-dim)' }}>
              {loading ? '…' : totalItems}
              <span style={{ fontSize: 13, color: 'var(--text-dim)', fontWeight: 600, marginLeft: 6 }}>items</span>
            </div>
          </div>
          <button
            onClick={runSeed}
            disabled={seeding}
            style={{
              padding: '10px 18px', borderRadius: 10, border: 'none', cursor: seeding ? 'wait' : 'pointer',
              background: seeding ? 'var(--surface2)' : 'var(--accent)', color: '#fff',
              fontWeight: 700, fontSize: 13, fontFamily: 'inherit', opacity: seeding ? 0.7 : 1,
            }}
          >
            {seeding ? 'Seeding…' : hasData ? '↻ Re-seed' : '⚡ Seed Knowledge Base'}
          </button>
        </div>

        {seedResult && (
          <div style={{ padding: '10px 12px', background: 'var(--green-bg)', border: '1px solid var(--green-border)', borderRadius: 10, fontSize: 12, color: 'var(--green)', marginBottom: 16 }}>
            {seedResult}
          </div>
        )}

        {!loading && stats.length === 0 && (
          <div style={{ padding: '20px', textAlign: 'center', color: 'var(--text-dim)', fontSize: 13 }}>
            No knowledge items yet. Run the SQL migration in Supabase first, then click Seed.
          </div>
        )}

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 10 }}>
          {Object.entries(CATEGORY_META).map(([cat, meta]) => {
            const stat = stats.find(s => s.category === cat)
            return (
              <div key={cat} style={{ background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: 12, padding: '12px 14px' }}>
                <div style={{ fontSize: 18, marginBottom: 6 }}>{meta.icon}</div>
                <div style={{ fontSize: 20, fontWeight: 900, color: stat ? meta.color : 'var(--text-dim)' }}>
                  {loading ? '…' : (stat?.count ?? 0)}
                </div>
                <div style={{ fontSize: 11, color: 'var(--text-dim)', fontWeight: 600 }}>{meta.label}</div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Phase 4 — Knowledge Curator */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: '20px', marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 4 }}>
              Knowledge Curator Agent
            </div>
            <div style={{ fontSize: 13, color: 'var(--text-dim)', lineHeight: 1.5 }}>
              Reviews 60 items per run · Flags outdated or inaccurate content · Runs weekly via cron
            </div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            {flaggedItems.length > 0 && (
              <div style={{ padding: '4px 10px', borderRadius: 20, background: 'var(--yellow-bg)', border: '1px solid var(--yellow-border)', fontSize: 11, fontWeight: 800, color: 'var(--yellow)' }}>
                {flaggedItems.length} flagged
              </div>
            )}
            <button
              onClick={runCurator}
              disabled={curating}
              style={{
                padding: '10px 18px', borderRadius: 10, border: 'none', cursor: curating ? 'wait' : 'pointer',
                background: curating ? 'var(--surface2)' : 'var(--blue)', color: '#fff',
                fontWeight: 700, fontSize: 13, fontFamily: 'inherit', opacity: curating ? 0.7 : 1,
              }}
            >
              {curating ? 'Running…' : '🤖 Run Curator Now'}
            </button>
          </div>
        </div>

        {curateResult && (
          <div style={{ padding: '10px 12px', background: 'var(--green-bg)', border: '1px solid var(--green-border)', borderRadius: 10, fontSize: 12, color: 'var(--green)', marginBottom: 16 }}>
            {curateResult}
          </div>
        )}

        {flaggedItems.length === 0 ? (
          <div style={{ padding: '20px', textAlign: 'center', color: 'var(--text-dim)', fontSize: 13, background: 'var(--surface2)', borderRadius: 12 }}>
            No flagged items — knowledge store is clean. Run the curator to scan for outdated content.
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {flaggedItems.map(item => {
              const isExpanded = expandedId === item.id
              const isReviewing = reviewingId === item.id
              const catMeta = CATEGORY_META[item.category]
              return (
                <div key={item.id} style={{ background: 'var(--surface2)', border: '1px solid var(--yellow-border)', borderRadius: 12, overflow: 'hidden' }}>
                  {/* Header row */}
                  <div
                    onClick={() => setExpandedId(isExpanded ? null : item.id)}
                    style={{ display: 'flex', alignItems: 'flex-start', gap: 12, padding: '12px 14px', cursor: 'pointer' }}
                  >
                    <span style={{ fontSize: 16, flexShrink: 0 }}>{catMeta?.icon ?? '📄'}</span>
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ fontSize: 13, fontWeight: 800, marginBottom: 2 }}>{item.title}</div>
                      <div style={{ fontSize: 11, color: 'var(--text-dim)' }}>{item.flag_reason}</div>
                    </div>
                    <div style={{ display: 'flex', gap: 6, flexShrink: 0 }}>
                      <span style={{ fontSize: 10, padding: '2px 7px', borderRadius: 10, background: 'var(--surface)', border: '1px solid var(--border)', color: 'var(--text-dim)', fontWeight: 700 }}>
                        v{item.version ?? 1}
                      </span>
                      <span style={{ fontSize: 12, color: 'var(--text-dim)' }}>{isExpanded ? '▲' : '▼'}</span>
                    </div>
                  </div>

                  {/* Expanded detail */}
                  {isExpanded && (
                    <div style={{ padding: '0 14px 14px' }}>
                      <div style={{ fontSize: 10, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: 6 }}>
                        Current Content
                      </div>
                      <div style={{ fontSize: 11, color: 'var(--text-dim)', lineHeight: 1.6, marginBottom: 12, padding: '10px', background: 'var(--surface)', borderRadius: 8 }}>
                        {item.content}
                      </div>

                      <div style={{ fontSize: 10, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: 6 }}>
                        Suggested Update
                      </div>
                      <textarea
                        value={editContent[item.id] ?? item.suggested_content ?? ''}
                        onChange={e => setEditContent(prev => ({ ...prev, [item.id]: e.target.value }))}
                        rows={5}
                        style={{
                          width: '100%', boxSizing: 'border-box', padding: '10px', borderRadius: 8,
                          background: 'var(--surface)', border: '1px solid var(--border)',
                          color: 'var(--text)', fontSize: 11, lineHeight: 1.6, fontFamily: 'inherit',
                          resize: 'vertical',
                        }}
                      />

                      <div style={{ display: 'flex', gap: 8, marginTop: 10 }}>
                        <button
                          onClick={() => reviewItem(item.id, 'accept')}
                          disabled={isReviewing}
                          style={{
                            padding: '8px 16px', borderRadius: 8, border: 'none', cursor: isReviewing ? 'wait' : 'pointer',
                            background: 'var(--green)', color: '#fff', fontWeight: 700, fontSize: 12,
                            fontFamily: 'inherit', opacity: isReviewing ? 0.7 : 1,
                          }}
                        >
                          {isReviewing ? 'Saving…' : '✓ Accept Update'}
                        </button>
                        <button
                          onClick={() => reviewItem(item.id, 'dismiss')}
                          disabled={isReviewing}
                          style={{
                            padding: '8px 16px', borderRadius: 8, border: '1px solid var(--border)', cursor: isReviewing ? 'wait' : 'pointer',
                            background: 'transparent', color: 'var(--text-dim)', fontWeight: 700, fontSize: 12,
                            fontFamily: 'inherit', opacity: isReviewing ? 0.7 : 1,
                          }}
                        >
                          Dismiss
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        )}
      </div>

      {/* Setup checklist */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: '20px', marginBottom: 20 }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 16 }}>
          Setup Checklist
        </div>
        {[
          {
            label: 'Run SQL migration in Supabase',
            sub: 'supabase/migrations/20260526_pgvector_knowledge.sql — enables pgvector + creates knowledge_items table + match_knowledge function',
            done: hasData,
          },
          {
            label: 'Run Phase 4 curator migration',
            sub: 'supabase/migrations/20260527_knowledge_curator.sql — adds version, flagged_for_review, flag_reason, suggested_content columns',
            done: true,
          },
          {
            label: 'Add OPENAI_API_KEY to Vercel',
            sub: 'Required for embedding text into vectors. Add in Vercel → Project → Settings → Environment Variables.',
            done: true,
          },
          {
            label: 'Seed knowledge base',
            sub: `${totalItems} items embedded. Includes training principles, sport protocols, rehab protocols, and exercise library.`,
            done: hasData,
          },
        ].map((step, i) => (
          <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start', padding: '10px 0', borderBottom: i < 3 ? '1px solid var(--border)' : 'none' }}>
            <div style={{
              width: 22, height: 22, borderRadius: '50%', flexShrink: 0, marginTop: 2,
              background: step.done ? 'var(--green)' : 'var(--surface2)',
              border: `1.5px solid ${step.done ? 'var(--green)' : 'var(--border)'}`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 11, color: step.done ? '#fff' : 'var(--text-dim)', fontWeight: 800,
            }}>
              {step.done ? '✓' : i + 1}
            </div>
            <div>
              <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 2 }}>{step.label}</div>
              <div style={{ fontSize: 11, color: 'var(--text-dim)', lineHeight: 1.5 }}>{step.sub}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Phase roadmap */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: '20px' }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 16 }}>
          APIE Roadmap
        </div>
        {[
          { phase: 'Phase 1', title: 'Domain Knowledge Store', status: 'LIVE', color: 'var(--green)', desc: 'pgvector + embeddings + retrieval wired into plan generation' },
          { phase: 'Phase 2', title: 'Agent Council v1', status: 'LIVE', color: 'var(--green)', desc: 'S&C Agent + PT/Rehab Agent with veto logic for restricted athletes' },
          { phase: 'Phase 3', title: 'Full Agent Council', status: 'LIVE', color: 'var(--green)', desc: 'Sports Specialist Agent + Mobility Agent + Mindset Agent + Recovery Agent' },
          { phase: 'Phase 4', title: 'Knowledge Curator Agent', status: 'LIVE', color: 'var(--green)', desc: 'Weekly cron reviews 60 items per pass, flags outdated content for admin review, versions knowledge store' },
        ].map((p, i) => (
          <div key={i} style={{ display: 'flex', gap: 14, padding: '12px 0', borderBottom: i < 3 ? '1px solid var(--border)' : 'none' }}>
            <div style={{ flexShrink: 0, paddingTop: 2 }}>
              <span style={{ fontSize: 10, fontWeight: 800, padding: '3px 8px', borderRadius: 20, background: p.status === 'LIVE' ? 'var(--green-bg)' : p.status === 'NEXT' ? 'var(--yellow-bg)' : 'var(--surface2)', color: p.color, border: `1px solid ${p.status === 'LIVE' ? 'var(--green-border)' : p.status === 'NEXT' ? 'var(--yellow-border)' : 'var(--border)'}` }}>
                {p.status}
              </span>
            </div>
            <div>
              <div style={{ fontSize: 13, fontWeight: 800, marginBottom: 2 }}>{p.phase} — {p.title}</div>
              <div style={{ fontSize: 11, color: 'var(--text-dim)', lineHeight: 1.5 }}>{p.desc}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
