'use client'
import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'

type KnowledgeStat = { category: string; count: number }

const CATEGORY_META: Record<string, { label: string; icon: string; color: string }> = {
  training_principle: { label: 'Training Principles',  icon: '🧠', color: 'var(--accent)' },
  sport_protocol:     { label: 'Sport Protocols',      icon: '🏆', color: 'var(--green)' },
  rehab_protocol:     { label: 'Rehab Protocols',      icon: '🩹', color: 'var(--blue)' },
  exercise:           { label: 'Exercise Library',     icon: '💪', color: 'var(--orange)' },
  nutrition_principle:{ label: 'Nutrition Principles', icon: '🥗', color: 'var(--yellow)' },
}

export default function MIETab() {
  const [stats, setStats] = useState<KnowledgeStat[]>([])
  const [loading, setLoading] = useState(true)
  const [seeding, setSeeding] = useState(false)
  const [seedResult, setSeedResult] = useState<string | null>(null)
  const [buildingIndex, setBuildingIndex] = useState(false)

  async function loadStats() {
    setLoading(true)
    try {
      const { data } = await supabase
        .from('knowledge_items')
        .select('category')
      if (data) {
        const counts: Record<string, number> = {}
        for (const row of data) {
          counts[row.category] = (counts[row.category] ?? 0) + 1
        }
        setStats(Object.entries(counts).map(([category, count]) => ({ category, count })))
      }
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { loadStats() }, [])

  async function runSeed() {
    setSeeding(true)
    setSeedResult(null)
    try {
      const res = await fetch('/api/admin/seed-knowledge', { method: 'POST' })
      const data = await res.json()
      setSeedResult(data.message ?? data.error ?? 'Done')
      await loadStats()
    } catch (e) {
      setSeedResult(String(e))
    } finally {
      setSeeding(false)
    }
  }

  const totalItems = stats.reduce((s, r) => s + r.count, 0)
  const hasData = totalItems > 0

  return (
    <div>
      <div style={{ marginBottom: 24 }}>
        <h2 style={{ fontSize: 22, fontWeight: 900, letterSpacing: '-0.02em', marginBottom: 4 }}>
          Multi-agent Intelligence Engine
        </h2>
        <p style={{ fontSize: 13, color: 'var(--text-dim)', lineHeight: 1.6 }}>
          MIE Phase 1 &amp; 2 — Domain Knowledge Store + Agent Council. Plans are now generated by a
          S&amp;C Agent using retrieved domain knowledge, with a PT/Rehab Agent safety review for
          athletes with injury restrictions.
        </p>
      </div>

      {/* Architecture diagram */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: '20px', marginBottom: 20 }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 16 }}>
          Generation Pipeline
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
          {[
            { icon: '🗄️', label: 'Knowledge Store', sub: 'pgvector retrieval', color: 'var(--blue)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '💪', label: 'S&C Agent', sub: 'Drafts the plan', color: 'var(--accent)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '🩹', label: 'PT/Rehab Agent', sub: 'Safety (injured only)', color: 'var(--blue)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '🏆', label: 'Sports Specialist', sub: 'Sport-specific depth', color: 'var(--orange)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '🧘', label: 'Mobility Agent', sub: 'Movement quality', color: 'var(--purple)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '🧠', label: 'Mindset Agent', sub: 'Warrior philosophy', color: 'var(--accent)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '🔋', label: 'Recovery Agent', sub: 'Rest day science', color: 'var(--green)' },
            { icon: '→', label: '', sub: '', color: 'var(--text-dim)' },
            { icon: '✅', label: 'Final Plan', sub: 'Returned to athlete', color: 'var(--yellow)' },
          ].map((step, i) =>
            step.label ? (
              <div key={i} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, padding: '10px 14px', background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: 12, minWidth: 110 }}>
                <span style={{ fontSize: 18 }}>{step.icon}</span>
                <span style={{ fontSize: 11, fontWeight: 800, color: step.color }}>{step.label}</span>
                <span style={{ fontSize: 10, color: 'var(--text-dim)', textAlign: 'center' }}>{step.sub}</span>
              </div>
            ) : (
              <span key={i} style={{ fontSize: 18, color: 'var(--text-dim)' }}>→</span>
            )
          )}
        </div>
      </div>

      {/* Knowledge store stats */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: '20px', marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 4 }}>
              Knowledge Store
            </div>
            <div style={{ fontSize: 28, fontWeight: 900, color: hasData ? 'var(--accent)' : 'var(--text-dim)' }}>
              {loading ? '…' : totalItems}
              <span style={{ fontSize: 13, color: 'var(--text-dim)', fontWeight: 600, marginLeft: 6 }}>items</span>
            </div>
          </div>
          <button
            onClick={runSeed}
            disabled={seeding}
            style={{
              padding: '10px 18px', borderRadius: 10, border: 'none', cursor: seeding ? 'wait' : 'pointer',
              background: seeding ? 'var(--surface2)' : 'var(--accent)', color: '#fff',
              fontWeight: 700, fontSize: 13, fontFamily: 'inherit', opacity: seeding ? 0.7 : 1,
            }}
          >
            {seeding ? 'Seeding…' : hasData ? '↻ Re-seed' : '⚡ Seed Knowledge Base'}
          </button>
        </div>

        {seedResult && (
          <div style={{ padding: '10px 12px', background: 'var(--green-bg)', border: '1px solid var(--green-border)', borderRadius: 10, fontSize: 12, color: 'var(--green)', marginBottom: 16 }}>
            {seedResult}
          </div>
        )}

        {!loading && stats.length === 0 && (
          <div style={{ padding: '20px', textAlign: 'center', color: 'var(--text-dim)', fontSize: 13 }}>
            No knowledge items yet. Run the SQL migration in Supabase first, then click Seed.
          </div>
        )}

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 10 }}>
          {Object.entries(CATEGORY_META).map(([cat, meta]) => {
            const stat = stats.find(s => s.category === cat)
            return (
              <div key={cat} style={{ background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: 12, padding: '12px 14px' }}>
                <div style={{ fontSize: 18, marginBottom: 6 }}>{meta.icon}</div>
                <div style={{ fontSize: 20, fontWeight: 900, color: stat ? meta.color : 'var(--text-dim)' }}>
                  {loading ? '…' : (stat?.count ?? 0)}
                </div>
                <div style={{ fontSize: 11, color: 'var(--text-dim)', fontWeight: 600 }}>{meta.label}</div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Setup checklist */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: '20px', marginBottom: 20 }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 16 }}>
          Setup Checklist
        </div>
        {[
          {
            label: 'Run SQL migration in Supabase',
            sub: 'supabase/migrations/20260526_pgvector_knowledge.sql — enables pgvector + creates knowledge_items table + match_knowledge function',
            done: hasData,
          },
          {
            label: 'Add OPENAI_API_KEY to Vercel',
            sub: 'Required for embedding text into vectors. Add in Vercel → Project → Settings → Environment Variables.',
            done: true, // can't verify from client, assume done if seed worked
          },
          {
            label: 'Seed knowledge base',
            sub: `${totalItems} items embedded. Includes training principles, sport protocols, rehab protocols, and exercise library.`,
            done: hasData,
          },
          {
            label: 'Build ivfflat index (after seeding)',
            sub: 'Run: CREATE INDEX ON knowledge_items USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100); — speeds up similarity search at scale.',
            done: false,
          },
        ].map((step, i) => (
          <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start', padding: '10px 0', borderBottom: i < 3 ? '1px solid var(--border)' : 'none' }}>
            <div style={{
              width: 22, height: 22, borderRadius: '50%', flexShrink: 0, marginTop: 2,
              background: step.done ? 'var(--green)' : 'var(--surface2)',
              border: `1.5px solid ${step.done ? 'var(--green)' : 'var(--border)'}`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 11, color: step.done ? '#fff' : 'var(--text-dim)', fontWeight: 800,
            }}>
              {step.done ? '✓' : i + 1}
            </div>
            <div>
              <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 2 }}>{step.label}</div>
              <div style={{ fontSize: 11, color: 'var(--text-dim)', lineHeight: 1.5 }}>{step.sub}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Phase roadmap */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, padding: '20px' }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-dim)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 16 }}>
          MIE Roadmap
        </div>
        {[
          { phase: 'Phase 1', title: 'Domain Knowledge Store', status: 'LIVE', color: 'var(--green)', desc: 'pgvector + embeddings + retrieval wired into plan generation' },
          { phase: 'Phase 2', title: 'Agent Council v1', status: 'LIVE', color: 'var(--green)', desc: 'S&C Agent + PT/Rehab Agent with veto logic for restricted athletes' },
          { phase: 'Phase 3', title: 'Full Agent Council', status: 'LIVE', color: 'var(--green)', desc: 'Sports Specialist Agent + Mobility Agent + Mindset Agent + Recovery Agent' },
          { phase: 'Phase 4', title: 'Knowledge Curator Agent', status: 'PLANNED', color: 'var(--text-dim)', desc: 'Background job monitors research sources, flags updates for admin review, versions knowledge' },
        ].map((p, i) => (
          <div key={i} style={{ display: 'flex', gap: 14, padding: '12px 0', borderBottom: i < 3 ? '1px solid var(--border)' : 'none' }}>
            <div style={{ flexShrink: 0, paddingTop: 2 }}>
              <span style={{ fontSize: 10, fontWeight: 800, padding: '3px 8px', borderRadius: 20, background: p.status === 'LIVE' ? 'var(--green-bg)' : p.status === 'NEXT' ? 'var(--yellow-bg)' : 'var(--surface2)', color: p.color, border: `1px solid ${p.status === 'LIVE' ? 'var(--green-border)' : p.status === 'NEXT' ? 'var(--yellow-border)' : 'var(--border)'}` }}>
                {p.status}
              </span>
            </div>
            <div>
              <div style={{ fontSize: 13, fontWeight: 800, marginBottom: 2 }}>{p.phase} — {p.title}</div>
              <div style={{ fontSize: 11, color: 'var(--text-dim)', lineHeight: 1.5 }}>{p.desc}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
