import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = { title: 'Terms of Service — Atlas Prime' }

const EFFECTIVE = 'May 7, 2026'

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px 80px' }}>

      {/* Header */}
      <div style={{ marginBottom: 40 }}>
        <Link href="/auth" style={{ fontSize: 13, color: 'var(--text-dim)', textDecoration: 'none', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: 6, marginBottom: 28 }}>
          ← Back
        </Link>
        <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--accent)', marginBottom: 10 }}>
          Legal
        </div>
        <h1 style={{ fontSize: 32, fontWeight: 900, letterSpacing: '-0.02em', marginBottom: 8 }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 13, color: 'var(--text-dim)' }}>
          Effective {EFFECTIVE} &nbsp;·&nbsp; Last updated {EFFECTIVE}
        </p>
      </div>

      <Section title="1. Acceptance of Terms">
        <P>By creating an account or using Atlas Prime (&quot;the Service,&quot; &quot;we,&quot; &quot;us&quot;), you agree to these Terms of Service. If you do not agree, do not use the Service.</P>
        <P>These terms apply to all users, including coaches and athletes. Your continued use after any update constitutes acceptance of the revised terms.</P>
      </Section>

      <Section title="2. What Atlas Prime Is">
        <P>Atlas Prime is a personalized training and recovery platform that uses AI to generate workout programs, track progress, and deliver coaching guidance. The Service is designed to complement — not replace — qualified medical, physical therapy, or professional coaching advice.</P>
        <P><strong style={{ color: 'var(--text)' }}>Atlas Prime is not a medical device and does not provide medical diagnoses, treatment plans, or physical therapy.</strong> Always consult a licensed healthcare provider before beginning any new exercise program, especially if you have injuries, chronic conditions, or have recently had surgery.</P>
      </Section>

      <Section title="3. AI-Generated Content">
        <P>Workout programs, exercise recommendations, and coaching cues in Atlas Prime are generated by artificial intelligence. AI output is probabilistic and may not be appropriate for every individual in every situation. You assume responsibility for:</P>
        <UL items={[
          'Evaluating AI-generated programs against your own physical condition and limitations.',
          'Modifying or skipping exercises that cause pain or discomfort.',
          'Seeking guidance from a licensed professional when in doubt.',
        ]} />
        <P>We continuously improve our models and content, but we make no guarantee that AI-generated content is error-free or perfectly suited to your needs.</P>
      </Section>

      <Section title="4. Your Account">
        <P>You are responsible for maintaining the security of your account credentials. You must not share your login or allow others to access your account. Notify us immediately at the contact address below if you suspect unauthorized access.</P>
        <P>You must be at least 13 years old to use the Service. Users under 18 should have parental or guardian consent.</P>
        <P>You agree to provide accurate information during registration and keep your profile up to date. Impersonating another person or creating fraudulent accounts is prohibited.</P>
      </Section>

      <Section title="5. Acceptable Use">
        <P>You agree not to:</P>
        <UL items={[
          'Use the Service for any unlawful purpose or in violation of any applicable law.',
          'Attempt to gain unauthorized access to any part of the Service or its underlying infrastructure.',
          'Reverse-engineer, scrape, or copy the Service or its AI models.',
          'Upload content that is abusive, harassing, or infringes on another party\'s intellectual property.',
          'Use the Service in a way that could harm or endanger yourself or others.',
        ]} />
      </Section>

      <Section title="6. Coach Accounts">
        <P>Users with a Coach account agree to additional responsibilities: you are solely responsible for the programs you build and deliver to your clients through Atlas Prime. Atlas Prime provides tools; you provide professional judgment. Do not use the platform to deliver programs to clients with conditions that require clinical supervision unless you hold the appropriate credentials.</P>
      </Section>

      <Section title="7. Admin Access">
        <P>Atlas Prime platform administrators may access your account using a limited-scope impersonation feature for support and quality-assurance purposes. All such access is logged with a timestamp, the administrator&apos;s identity, and a stated reason. Impersonation sessions expire automatically and cannot be used to change your password or payment credentials. For full details, see our Privacy Policy.</P>
      </Section>

      <Section title="8. Intellectual Property">
        <P>The Atlas Prime platform, including its design, code, AI models, and exercise library, is our intellectual property. These terms do not grant you any ownership rights.</P>
        <P>You retain ownership of the personal data you provide (your profile, logs, and notes). By using the Service, you grant us a limited license to process that data in order to provide and improve the Service.</P>
      </Section>

      <Section title="9. Disclaimers and Limitation of Liability">
        <P>The Service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee uninterrupted availability, accuracy of AI outputs, or fitness for a particular purpose.</P>
        <P>To the fullest extent permitted by law, Atlas Prime will not be liable for any indirect, incidental, or consequential damages arising from your use of the Service, including but not limited to personal injury arising from following workout programming.</P>
      </Section>

      <Section title="10. Termination">
        <P>You may delete your account at any time from the Account page. We may suspend or terminate accounts that violate these terms, with or without notice depending on the severity of the violation.</P>
        <P>Upon termination, your data will be handled in accordance with our Privacy Policy and any applicable data retention requirements.</P>
      </Section>

      <Section title="11. Changes to These Terms">
        <P>We may update these terms as the Service evolves. Significant changes will be communicated via email or an in-app notice. Your continued use after the effective date of an update constitutes acceptance.</P>
      </Section>

      <Section title="12. Contact">
        <P>Questions about these terms? Use the feedback option in the Account page inside the app, or reach out through the support channel listed there.</P>
      </Section>

      <div style={{ marginTop: 40, paddingTop: 24, borderTop: '1px solid var(--border)', display: 'flex', gap: 20, flexWrap: 'wrap' }}>
        <Link href="/legal/privacy" style={{ fontSize: 13, color: 'var(--accent)', textDecoration: 'none', fontWeight: 600 }}>
          Privacy Policy →
        </Link>
        <Link href="/auth" style={{ fontSize: 13, color: 'var(--text-dim)', textDecoration: 'none' }}>
          Back to sign up
        </Link>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 16, fontWeight: 700, color: 'var(--text)', marginBottom: 12, letterSpacing: '-0.01em' }}>
        {title}
      </h2>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {children}
      </div>
    </div>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ fontSize: 14, color: 'var(--text-mid)', lineHeight: 1.75 }}>{children}</p>
}

function UL({ items }: { items: string[] }) {
  return (
    <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 6 }}>
      {items.map((item, i) => (
        <li key={i} style={{ fontSize: 14, color: 'var(--text-mid)', lineHeight: 1.7 }}>{item}</li>
      ))}
    </ul>
  )
}
